### ISSUE TITLE
Create console command to run installation commands at once

### ISSUE THREAD

**Issue by kakposoe** [range-of-motion/budget#10]
Hi there. Saw your project while browsing through the larachat projects channel.

Firstly, great work on this project. 

I wanted to suggest creating a new command which would compile all of the separate installation commands into once (e.g. `php artisan budget:install`).

Taking it one step further, prompts (and actions) can be given to making sure users have either `npm` or `yarn` on their system before compiling.

Let me know your thoughts on this.

**Comment by range-of-motion** [comment]
Thanks for the kind words! I have been thinking about this and while I didn't see the need for it, I might consider it. I'm wondering, do you prefer an artisan command or a shell script?

**Comment by kakposoe** [comment]
Shell script may be better.

If you would like, I don't mind contributing to this.

**Comment by range-of-motion** [comment]
@kakposoe Why would a shell script be better?

**Comment by kakposoe** [comment]
Using laravel to perform shell command involves using `symfony/process` (if I am correct). It may be overkill for this process.

**Comment by sebastiaanspeck** [comment]
Since this issue is open for quite a while, I will look into this, this weekend

**Comment by range-of-motion** [comment]
Done in #32.
