### ISSUE TITLE
.env.example

### ISSUE THREAD

**Issue by Falkon81** [range-of-motion/budget#112]
**Expected behavior**

What should happen?

**Current behavior**

What's happening right now when trying to perform your desired action?

**Steps to reproduce**

1. Go to ABC
2. Click on XYZ
3. Explosions and thunderstorms appear

*If applicable, screenshots can be added here*

**Comment by range-of-motion** [comment]
Thanks for submitting an issue. I think you forgot to replace the example text tho. What's the problem?

**Comment by Falkon81** [comment]
Thanks

**Comment by Falkon81** [comment]
> Thanks

**Comment by Falkon81** [comment]
Bug label

**Comment by Falkon81** [comment]
> **Expected behavior**
> 
> What should happen?
> 
> **Current behavior**
> 
> What's happening right now when trying to perform your desired action?
> 
> **Steps to reproduce**
> 
> 1. Go to ABC
> 2. Click on XYZ
> 3. Explosions and thunderstorms appear
> 
> *If applicable, screenshots can be added here*
>

**Comment by Falkon81** [comment]
Thanks

**Comment by range-of-motion** [comment]
Buh-bye 👋
