### ISSUE TITLE
> **Expected behavior** good

### ISSUE THREAD

**Issue by Falkon81** [range-of-motion/budget#114]
> **Expected behavior**
> 
> What should happen?
> 
> **Current behavior**
> 
> What's happening right now when trying to perform your desired action?
> 
> **Steps to reproduce**
> 
> 1. Go to ABC
> 2. Click on XYZ
> 3. Explosions and thunderstorms appear
> 
> *If applicable, screenshots can be added here*
> 

_Originally posted by @Falkon81 in https://github.com/range-of-motion/budget/issues/112#issuecomment-634081807_

**Comment by Falkon81** [comment]
Bug label

**Comment by Falkon81** [comment]
> > **Expected behavior**
> > 
> > What should happen?
> > 
> > **Current behavior**
> > 
> > What's happening right now when trying to perform your desired action?
> > 
> > **Steps to reproduce**
> > 
> > 1. Go to ABC
> > 2. Click on XYZ
> > 3. Explosions and thunderstorms appear
> > 
> > *If applicable, screenshots can be added here*
> > 
> 
> 
> 
> _Originally posted by @Falkon81 in https://github.com/range-of-motion/budget/issues/112#issuecomment-634081807_

**Comment by range-of-motion** [comment]
Buh-bye 👋
