### ISSUE TITLE
Insert south american currencies

### ISSUE THREAD

**Issue by daniel-leandro** [range-of-motion/budget#134]
I'm trying to use in Brazil, but there's not found our currency "Brazilian Real BRL". 

I will create a pull request with the main currencies from South American countries.

**Comment by daniel-leandro** [comment]
Created PR #135

**Comment by range-of-motion** [comment]
Thank you very much for your contribution @daniel-leandro! Your PR has been merged, and I'm aiming to include it in v0.4.
