### ISSUE TITLE
No budgeting features?

### ISSUE THREAD

**Issue by ARandomOWL** [range-of-motion/budget#152]
Despite having the name _Budget_, the software doesn't list any actual budgeting features and appears to be more of an accounting software.

Am I wrong, or are there implied budgeting features? I was drawn here by the name but haven't tried the software as it doesn't seem to fit my needs.

**Comment by range-of-motion** [comment]
You'd be right.

There *used to be* a feature where you could see a budget, and see a bar that represented how far along the budget you were. But I found it to be a weak implementation, so I decided to remove it altogether and think of a better alternative.

Perhaps that time is now. What should a budget do for you? I'd like to know 🙂

**Comment by PipeItToDevNull** [comment]
That bar would honestly be enough for me. I am not looking to track every dollar, I just want to get my 'ooh shiny' impulse handled.

**Comment by range-of-motion** [comment]
Fair enough 😉  It's on the roadmap.

**Comment by range-of-motion** [comment]
Done in #187.
