### ISSUE TITLE
Ability to import transactions from Revolut

### ISSUE THREAD

**Issue by range-of-motion** [range-of-motion/budget#155]
I think that's a good start for integrating with other banks/payment providers.

**Comment by mvmisha** [comment]
I'd suggest checking up the following issue from another repo, maybe it will help with your implementation

https://github.com/tducret/revolut-python/issues/17

**Comment by range-of-motion** [comment]
Thanks, I'll check it out.

**Comment by range-of-motion** [comment]
Going to close this for now, as I'm focussing on Plaid. Unfortunately that doesn't Revolut, but I don't mind. If somebody does, please re-open.
