### ISSUE TITLE
option to disabled login screen 

### ISSUE THREAD

**Issue by retconned** [range-of-motion/budget#163]
I hosted this app on my personal PC and I want the option to disable the log screen so when I type localhost I get greeted with my dashboard

**Comment by ryangjchandler** [comment]
@range-of-motion happy to open a PR for this one.

**Comment by range-of-motion** [comment]
@ryangjchandler let's go 💨

**Comment by ryangjchandler** [comment]
@range-of-motion I'm thinking the best way would be a config / .env option - requires no other configuration, then based on that value redirect to the dashboard when trying to access the login / register pages.

**Comment by range-of-motion** [comment]
Right, but you gotta fake the authentication. So you'd have something along the lines of a `AUTOMATICALLY_AUTHENTICATE_USER_ID` setting, or whatever 🤷

**Comment by ryangjchandler** [comment]
Yeah true - that assumes that a user has still been registered.

**Comment by range-of-motion** [comment]
Moving this up a milestone, since v0.6 is long overdue 😅

**Comment by nicoppola** [comment]
Hi! Just checking in if this was ever implemented or if there is another way to implement a no-login option?
