### ISSUE TITLE
E-mail field in account settings not checking for the right e-mail format

### ISSUE THREAD

**Issue by EmTeeAge** [range-of-motion/budget#168]
**Expected behavior**
In the Account settings, when changing the login e-mail, the box should only allow values formated as e-mail to be saved.

**Current behavior**
The e-mail field in the Account settings is set to input type "text", therefore allowing any value to be set. This causes issues when logging back in, because the login screen checks for the right format in the e-mail field. If you set your e-mail in the settings to "example" (or anything without '@'), you won't be able to log back in because the login screen has input type of "email" and will keep saying "Please enter an email adress". In order to log back in, the user has to modify the email login field to accept input other than email.

**Steps to reproduce**

1. Log in and go to the Settings
2. Select Account
3. Change the E-mail field to anything without '@', e.g. "example"
4. Click Save and Log out
5. Try to login with the value that you have set in the E-mail field before, e.g. "example"
6. You won't be able to log in if the saved value isn't formatted as email.

![image](https://user-images.githubusercontent.com/67438185/85787885-9b8e0f80-b71b-11ea-9410-360761e03343.png)

![image](https://user-images.githubusercontent.com/67438185/85787918-aa74c200-b71b-11ea-8aae-d30b356a316f.png)

![image](https://user-images.githubusercontent.com/67438185/85787936-b1033980-b71b-11ea-9a19-1e37a50987f5.png)

![image](https://user-images.githubusercontent.com/67438185/85787955-b8c2de00-b71b-11ea-92dd-1eb96d415236.png)

**Comment by range-of-motion** [comment]
Nicely found!

**Comment by range-of-motion** [comment]
Fixed in #172.
