### ISSUE TITLE
Integration with web-money-manager-ex

### ISSUE THREAD

**Issue by bingalls** [range-of-motion/budget#18]
https://github.com/moneymanagerex/web-money-manager-ex is also written in PHP, with many stable integrations. I find its desktop & mobile apps more user friendly than Gnu Cash.

**Comment by sebastiaanspeck** [comment]
That repo looks dead to me. If you can tell us, which features are missing in Budget, we can integrate them

**Comment by bingalls** [comment]
Definitely not dead, but as slow moving as GnuCash. You can see activity on https://forum.moneymanagerex.org/ and features on its home page https://www.moneymanagerex.org/
Its PHP code is really lagging, but GnuCash has no PHP code. MoneyManagerEX is more user friendly than GnuCash, especially its mobile port. I'd say the most important feature would be to import / export file formats. If you support Quickbooks QIF, then you'll have both GnuCash & MoneyManagerEX compatibility. I'd be interested to hear, which has the cleaner code base.

**Comment by sebastiaanspeck** [comment]
We can already import CSV, but QIF is a good addition. If we are integrating that, we will also introduce exporting functionality for CSV and QIF

**Comment by range-of-motion** [comment]
I fail to see why we would integrate with web-money-manager-ex. It looks like it's a product much like ours.

It's not because I'm against competition or anything, but I fail to see the benefits? What would be integrated?

**Comment by bingalls** [comment]
I'd like to see import/export between your projects. Their sqlite is a bit dicey, because it is versioned, and cannot be downgraded. QIF is the best format; hopefully, you can learn from their code.
