### ISSUE TITLE
Weekly reports doesn’t match

### ISSUE THREAD

**Issue by sebastiaanspeck** [range-of-motion/budget#21]
The weekly report-page seems to show a monthly-report and even has a hardcoded year in it.. If I change it to 2019, the report doesn’t match anymore. Please fix

**Comment by range-of-motion** [comment]
Ah. The famous "I'll fix it later", that then never gets fixed. Thanks for reporting, will fix!

**Comment by range-of-motion** [comment]
Oh, and by the way–the report is weekly. However the labels are monthly to prevent a clusterfuck of labels at the bottom.

**Comment by range-of-motion** [comment]
Done in #22.

**Comment by sebastiaanspeck** [comment]
> Oh, and by the way–the report is weekly. However the labels are monthly to prevent a clusterfuck of labels at the bottom.

Maybe a good idea to add extra labels then? Now it looks like a month-report because of the months displayed

**Comment by range-of-motion** [comment]
If you have any suggestions, create another issue for it. I'm down if it looks good.
