### ISSUE TITLE
Add Spent Today and Spent This Month card in dashboard 

### ISSUE THREAD

**Issue by abrardev99** [range-of-motion/budget#218]
In the dashboard, there is no option/card to see my spending. What I mean see below images. 

![image](https://user-images.githubusercontent.com/54532330/88329490-79e86e00-cd43-11ea-8a03-dde3428ef237.png)

**Comment by range-of-motion** [comment]
I've been thinking of implementing customizable cards for the dashboard. So you can pick from a range of cards (spent today, earned today, spent this month, balance, etc.), and rearrange them.

Would that be something you're interested in?

**Comment by range-of-motion** [comment]
It took a while, but I just merged #251–which implements dashboard customization through widgets.
