### ISSUE TITLE
Use relative path for redirect

### ISSUE THREAD

**Issue by windware-ono** [range-of-motion/budget#237]
When I access the root path as `https://my-budget-domain/` having nginx proxy in front of it, it redirects to `http://my-budget-domain/dashboard` as an absolute URL but it should be given a relative path of `/dashboard` for `Location` header as when I embed the app inside a https iframe, the content gets blocked as it tries to access http inside https during redirection.

It seems this happens on other links as well such as `/settings` for the `Settings` link in the menu.

**Comment by windware-ono** [comment]
There's also a http link for resending verification email but this can be a relative path too.

![budget-http-form](https://user-images.githubusercontent.com/4352236/94408825-4cd79200-01b0-11eb-99a1-d152aea935e8.png)

**Comment by range-of-motion** [comment]
I'm currently looking into this, however it looks like we're using Laravel's "recommended" way of redirecting, which is through [named routes](https://laravel.com/docs/8.x/redirects#redirecting-named-routes).

I'm afraid I can't do anything about the way that the framework works. If you think there's a sensible solution I'd love to hear about it 🙂

**Comment by range-of-motion** [comment]
I'm revisiting this.

I can make the paths relative by passing a 3rd argument to `route()` helper. If you still need this, please let me know and I'll re-open this.
