### ISSUE TITLE
Mobile interface broken for transactions

### ISSUE THREAD

**Issue by windware-ono** [range-of-motion/budget#238]
Layout seems broken on mobile for `/transactions`.

![budget-mobile-transactions](https://user-images.githubusercontent.com/4352236/94406229-a6d65880-01ac-11eb-9588-22b84a99d4e4.png)

**Comment by range-of-motion** [comment]
I'll try and address this in the upcoming release.

**Comment by windware-ono** [comment]
Thanks!

Also the positioning in the profile page was a bit off.

![budget-mobile-profile](https://user-images.githubusercontent.com/4352236/94408279-86f46400-01af-11eb-9dd2-2b545ddd0767.png)

**Comment by range-of-motion** [comment]
Done in #246.

I must admit I'm not that keen on the fix for the list of transactions, but since that is being reworked anyway it's probably not worth investing more time into it.
