### ISSUE TITLE
Set default as Spending for a new transaction

### ISSUE THREAD

**Issue by windware-ono** [range-of-motion/budget#239]
I assume most people have more spendings than earnings entries, so it's easier to input a new transaction if `Spending` is the default chosen type.

**Comment by range-of-motion** [comment]
What about freelancers or small businesses? They might have more earnings than spendings. I propose we turn this into a setting, that everybody can change for themselves. What do you think of this?

**Comment by windware-ono** [comment]
That sounds great.

**Comment by range-of-motion** [comment]
Alright then, this was done in #244.
