### ISSUE TITLE
Failed on php artisan migrate

### ISSUE THREAD

**Issue by tangramor** [range-of-motion/budget#284]
**Expected behavior**
```
$ php artisan migrate
```

What should happen?
Create database tables...

**Current behavior**
```
In Connection.php line 678:

  could not find driver (SQL: select * from information_schema.tables where table_schema = budget and table_name = migrations and table_type = 'BASE TABLE')


In Exception.php line 18:

  could not find driver


In PDOConnection.php line 38:

  could not find driver
```

What's happening right now when trying to perform your desired action?

**Steps to reproduce**

1. Ubuntu 20.04, git clone and checkout v0.9.2
2. Execute the setup steps described in README.md
3. Failed on `php artisan budget:install` and `php artisan migrate` steps

*If applicable, screenshots can be added here*
![image](https://user-images.githubusercontent.com/491287/107135316-aefd8c00-6934-11eb-8efe-02f21ad48a47.png)

**Comment by range-of-motion** [comment]
Can you show me the output of `php -m`?

**Comment by tangramor** [comment]
> php -m

php -m

[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by tangramor** [comment]
OK, I see what's the problem, it was fixed by `sudo apt install  php-mysql`
