### ISSUE TITLE
dependency on fzaninotto/faker is causing build errors

### ISSUE THREAD

**Issue by gorrilla10101** [range-of-motion/budget#287]
**Expected behavior**

What should happen?
docker-compose build should succeed
**Current behavior**
docker-compose build fails with error.
```
Your lock file does not contain a compatible set of packages.
```
What's happening right now when trying to perform your desired action?
The build is failing
**Steps to reproduce**

1. clone repository
2. run `docker-compose build`
3. 26 problems  appear

*If applicable, screenshots can be added here*

**Comment by gorrilla10101** [comment]
fzaninotto/faker has been abandoned and is preventing upgrading to versions above 7.2, while other libraries are moving forward and restricting to versions above 7.3
https://marmelab.com/blog/2020/10/21/sunsetting-faker.html

with a search https://github.com/FakerPHP/Faker/ might be a suitable replacement without to much work, maybe.

**Comment by range-of-motion** [comment]
It does indeed seem like `fzaninotto/faker` has been abandoned for `fakerphp/faker` since Laravel 8. I will try and migrate accordingly.

As far as Docker goes, try the `148-revamp-docker-setup` branch. It _should_ have everything you need. Be sure to read the docs that come with that branch tho.

**Comment by gorrilla10101** [comment]
Thanks, I will give the branch a shot.

**Comment by range-of-motion** [comment]
Did that work for you?

**Comment by gorrilla10101** [comment]
Switching to that branch solved the build errors. However, when I ran `docker-compose up -d` then it would exit with error code 127
 The error in the log was. 
```app_1       | /usr/local/bin/docker-php-entrypoint: 9: exec: ./docker_boot.sh: not found```

I played around to see if I could give you better information and I believe most of my issues revolve around permissions. 

I removed the docker_boot.sh from the compose file and modified the end of the dockerfile to copy everything in during build and set the ownership. this got me passed the dokcer_boot.sh
```
    WORKDIR /var/www 
    COPY . .
    RUN chown -R 1000:1000 /var/www
    ENTRYPOINT [ "sh", "docker_boot.sh" ]
```
This changed the error code to 2 but still wouldn't run. 
```
docker-compose logs app
Attaching to 25289aebdb710bb96afbfddfe75a7bc1218529b0516a162ea1c9a5ddd02a6b30_app_1
: not found | docker_boot.sh: 2: docker_boot.sh:
app_1       | chown: cannot access '/var/www/storage'$'\r': No such file or directory
: not found | docker_boot.sh: 4: docker_boot.sh:
app_1       | docker_boot.sh: 18: docker_boot.sh: Syntax error: end of file unexpected (expecting "then")
````

Might be relevant, I am using a windows 10 machine. I have tested it in Windows and using Ubuntu through WSL2.

**Comment by range-of-motion** [comment]
I'm unable to reproduce this on master currently, are you?

**Comment by gorrilla10101** [comment]
Away from my tech for the holidays. Will check it as soon as I get a chance nest week.

**Comment by range-of-motion** [comment]
No worries. Out of curiosity, do you still use this project? 🤔

**Comment by range-of-motion** [comment]
Whether or not this was actually causing you any trouble, I did move to `fakerphp/faker` in #354 🙂

**Comment by gorrilla10101** [comment]
Sorry, I swapped to something else for a while but I am back on the market. Thank you will give this another shot.

**Comment by range-of-motion** [comment]
No worries, just open up another issue if run into something. I'm doing a lot of upgrades right now.
