### ISSUE TITLE
SSL certificate of https://budget.pixely.me/ is broken

### ISSUE THREAD

**Issue by gempain** [range-of-motion/budget#289]
Hi, thought I'd let you know that the SSL certificate of https://budget.pixely.me/ is broken.
![Screen Shot 2021-04-07 at 14 33 29](https://user-images.githubusercontent.com/13135149/113867029-528ce080-97ae-11eb-93bb-74eee361d1b3.png)

**Comment by range-of-motion** [comment]
Thanks for the heads up, however we've moved to https://budgethq.com a while ago. How did you find that address? I thought I updated it everywhere 🤔

**Comment by gempain** [comment]
3rd line on your README 😅
![Screen Shot 2021-04-07 at 14 48 51](https://user-images.githubusercontent.com/13135149/113868915-77825300-97b0-11eb-8b38-8058da888751.png)

**Comment by range-of-motion** [comment]
D'oh. Thanks for reporting, I'll update it soon.

**Comment by gempain** [comment]
Close at your discretion 😉

**Comment by range-of-motion** [comment]
Done.

**Comment by gempain** [comment]
Sweet ! Keep up the great work 🙂
