### ISSUE TITLE
Feature Request: Different wallets

### ISSUE THREAD

**Issue by gringofe** [range-of-motion/budget#301]
I think the ability to add different "wallets" which represent different bank accounts or cash would be a nice feature. Transactions should then be linked to a wallet (e.g. I spent x€ cash on something or bought something online for y€ using my bank account). The dashboard should also show the sum of all wallets, and the balance of each wallet seperately.

**Comment by range-of-motion** [comment]
There's already support for different "spaces". It probably doesn't fully satisfy your needs, but should come close.

Say you have a personal bank account and a shared one (for you and your significant other for example), you can assign transactions to either spaces. You can even share a space with another user (in case your significant other also uses Budget).

**Comment by range-of-motion** [comment]
As I haven't heard from you for a while, I will go ahead and close this. If you think the current implementation of "spaces" is insufficient, please let me know and I'll be happy to look into it 🙂
