### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by dadwarf** [range-of-motion/budget#309]
Hi, 

Is there something missing in my debian ?

`thierry@debianServer:~/www/81/budget$ php artisan budget:install
00h00m00s 0/0: :
In BudgetInstall.php line 25:

  The command "'yarn' 'install'" failed.

  Exit Code: 1(General error)

  Working directory: /home/thierry/www/81/budget

  Output:
  ================

  Error Output:
  ================
  ERROR: [Errno 2] No such file or directory: 'install'

`

Thanks a lot

**Comment by range-of-motion** [comment]
Do you have Yarn installed? What's the output of `which yarn`?

**Comment by dadwarf** [comment]
Hi, thanks for your answer.
`thierry@debianServer:~/www/81/budget$ which yarn
/usr/bin/yarn`

**Comment by range-of-motion** [comment]
Weird, what happens if you run `yarn install` by yourself?

**Comment by dadwarf** [comment]
thierry@debianServer:~/www/81/budget$ yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

**Comment by dadwarf** [comment]
thierry@debianServer:~/www/81/budget$ ls -la
total 716
drwxr-xr-x 14 thierry thierry   4096 juin   3 18:26 .
drwxr-xr-x  3 thierry thierry   4096 juin   3 18:25 ..
drwxr-xr-x 14 thierry thierry   4096 juin   3 18:25 app
-rwxr-xr-x  1 thierry thierry   1646 juin   3 18:25 artisan
drwxr-xr-x  3 thierry thierry   4096 juin   3 18:25 bootstrap
-rw-r--r--  1 thierry thierry    101 juin   3 18:25 codecov.yml
-rw-r--r--  1 thierry thierry   2030 juin   3 18:25 composer.json
-rw-r--r--  1 thierry thierry 271878 juin   3 18:25 composer.lock
drwxr-xr-x  2 thierry thierry   4096 juin   3 18:25 config
-rw-r--r--  1 thierry thierry    517 juin   3 18:25 CONTRIBUTING.md
drwxr-xr-x  5 thierry thierry   4096 juin   3 18:25 database
-rwxr-xr-x  1 thierry thierry     85 juin   3 18:25 docker_boot.sh
-rw-r--r--  1 thierry thierry    887 juin   3 18:25 docker-compose.yml
-rw-r--r--  1 thierry thierry    928 juin   3 18:25 Dockerfile
-rw-r--r--  1 thierry thierry    143 juin   3 18:25 .editorconfig
-rw-r--r--  1 thierry thierry    706 juin   3 18:25 .env.ci
-rw-r--r--  1 thierry thierry    700 juin   3 18:25 .env.example
drwxr-xr-x  8 thierry thierry   4096 juin   3 18:25 .git
-rw-r--r--  1 thierry thierry    111 juin   3 18:25 .gitattributes
drwxr-xr-x  4 thierry thierry   4096 juin   3 18:25 .github
-rw-r--r--  1 thierry thierry    239 juin   3 18:25 .gitignore
-rw-r--r--  1 thierry thierry   1075 juin   3 18:25 LICENSE
-rw-r--r--  1 thierry thierry    664 juin   3 18:25 nginx.conf
-rw-r--r--  1 thierry thierry    762 juin   3 18:25 package.json
-rw-r--r--  1 thierry thierry    212 juin   3 18:25 phpcs.xml
-rw-r--r--  1 thierry thierry   1157 juin   3 18:25 phpunit.xml
drwxr-xr-x  3 thierry thierry   4096 juin   3 18:25 public
-rw-r--r--  1 thierry thierry   2654 juin   3 18:25 README.md
drwxr-xr-x  5 thierry thierry   4096 juin   3 18:25 resources
drwxr-xr-x  2 thierry thierry   4096 juin   3 18:25 routes
-rw-r--r--  1 thierry thierry    563 juin   3 18:25 server.php
drwxr-xr-x  5 thierry thierry   4096 juin   3 18:25 storage
drwxr-xr-x  5 thierry thierry   4096 juin   3 18:25 tests
drwxr-xr-x 35 thierry thierry   4096 juin   3 21:55 vendor
-rw-r--r--  1 thierry thierry     19 juin   3 21:55 version.txt
-rwxr-xr-x  1 thierry thierry   5318 juin   3 18:25 wait-for-it.sh
-rw-r--r--  1 thierry thierry    155 juin   3 18:25 webpack.mix.js
-rw-r--r--  1 thierry thierry 304600 juin   3 18:25 yarn.lock

**Comment by range-of-motion** [comment]
I suspect this is caused by your setup. I can only suggest you remove Yarn through apt and reinstall it through `npm install -g yarn`.

**Comment by dadwarf** [comment]
You are right, but my nodejs version also wrong :
thierry@debianServer:~/www/81/budget$ php artisan budget:install

In BudgetInstall.php line 25:

  The command "'yarn' 'install'" failed.

  Exit Code: 1(General error)

  Working directory: /home/thierry/www/81/budget

  Output:
  ================
  yarn install v1.22.10
  [1/4] Resolving packages...
  [2/4] Fetching packages...
  info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.


  Error Output:
  ================
  error laravel-mix@6.0.16: The engine "node" is incompatible with this module. Expected version ">=12.14.0". Got "10.24.0
  "
  error Found incompatible module.

**Comment by dadwarf** [comment]
That's ok with a newer version of nodejs !
Thanks a lot !
