### ISSUE TITLE
Potential Security Issue

### ISSUE THREAD

**Issue by JamieSlome** [range-of-motion/budget#312]
Hello,

We recently received a vulnerability disclosure from @ranjit-git against your repository. I couldn't find a security policy or contactable e-mail to share the vulnerability details with you.

If you can provide me with an e-mail, I can send it over to you? Otherwise, you can view the advisory [here](https://huntr.dev/bounties/1-range-of-motion/budget/).

It is private to only you and the discloser. If you have any questions, here to help!

-- Jamie from huntr.dev

**Comment by range-of-motion** [comment]
Are you on Discord? I'd prefer you contact me there, there's a link in the README.

**Comment by JamieSlome** [comment]
@range-of-motion - for sure, we have a Discord [server](https://huntr.dev) or you can add me @ JamieSlome#9817.

**Comment by range-of-motion** [comment]
Thanks for reporting this @JamieSlome.

It seems that Blade is able to output a string that Vue then proceeds to compile, thus causing this XSS attack. I have asked around and it seems like the only proper way to solve this is migrating from Vue.. 🤦‍♂️ 

*To be continued.*

**Comment by ranjit-git** [comment]
@range-of-motion found few way to prevent xss attack using vue
https://portswigger.net/research/evading-defences-using-vuejs-script-gadgets
https://portswigger.net/research/evading-defences-using-vuejs-script-gadgets
https://www.raymondcamden.com/2019/11/26/sanitizing-html-in-vuejs
https://stackoverflow.com/questions/55262267/does-vue-by-default-provide-security-for-or-protects-against-xss
https://shivkumarganesh.medium.com/prevent-xss-in-vue-js-using-google-caja-53a3f88c9b58

**Comment by ranjit-git** [comment]
Hi, @range-of-motion can you plz update the report status https://huntr.dev/bounties/1-range-of-motion/budget/ if you consider its a valid?

**Comment by range-of-motion** [comment]
Sorry, it's been a while since I've looked at this.

While I appreciate the effort, none of the aforementioned articles provided any solution to this problem. The XSS attacks might happen outside of a Vue component (but still inside the `id="app"` element). 

I would need to let Vue know at specific places that a Blade-induced XSS attack might occur there, and prevent it from parsing the `{{ }}` characters as useable JS.

**Comment by range-of-motion** [comment]
I found a thread that perfectly describes the problem I'm having (and possibly also a solution).

https://laracasts.com/discuss/channels/code-review/trying-to-prevent-cross-site-scripting

**Comment by range-of-motion** [comment]
Fixed in #343.
