### ISSUE TITLE
Can't view budgets page after deleting a tag

### ISSUE THREAD

**Issue by jjbofficial** [range-of-motion/budget#313]
**Expected behaviour**
Be able to view a list of created budgets

**Current behaviour**
The budgets page returns an error 500

What's happening right now when trying to perform your desired action?

**Steps to reproduce**

1. Create a tag
2. Create a budget for that tag
3. Delete the tag
4. Click on "Budgets" in the navbar

*If applicable, screenshots can be added here*
![Screenshot from 2021-06-23 18-52-29](https://user-images.githubusercontent.com/24777420/123152558-3ebf5500-d454-11eb-9a4c-6902d96bff17.png)

**Comment by range-of-motion** [comment]
Thanks for reporting, I'm able to reproduce this as well. I'm going to work on a fix.

**Comment by range-of-motion** [comment]
@jjbofficial do you want to review it? I pushed it to #314.

**Comment by jjbofficial** [comment]
Everything looks good.
