### ISSUE TITLE
Email to verify account is not sent

### ISSUE THREAD

**Issue by jjbofficial** [range-of-motion/budget#315]
**Expected behavior**
An email is sent to the user which contains a link that when they click, they can verify the email address they used to register for an account

**Current behavior**
The user does not receive the email and clicking resend does not resend the email

What's happening right now when trying to perform your desired action?

**Steps to reproduce**

1. Register an account
2. Check your email (both inbox and spam folders) for the verification email
3. Wait a few minutes ( eg. 10 minutes) and repeat step 2
4. Click resend
5. Repeat step 3

*If applicable, screenshots can be added here*
![Screenshot from 2021-06-23 20-52-54](https://user-images.githubusercontent.com/24777420/123167240-d2e5e800-d465-11eb-8093-fd46cf84e4d4.png)

**Comment by range-of-motion** [comment]
I don't think this is a bug with the app itself, but rather the instance I set up publicly. I will take a look at it soon. Remind if me I forget.

**Comment by jjbofficial** [comment]
The emails are being sent now
