### ISSUE TITLE
CSV imports

### ISSUE THREAD

**Issue by dadwarf** [range-of-motion/budget#322]
Hi, i try to import my CSV from this format :

06/08/2021,"ACHAT CB GVB VOERTUIG B 05.08.21 EUR         12.80 CARTE NO  222  ",-12.80,-83.96
06/08/2021,"ACHAT CB CRV WWW.EPSILO 05.08.21 EUR          1.00 CARTE NO  222  ",-1.00,-6.56

But it doesn't work..how do i need to format it ?
Thanks
Thierry

**Comment by range-of-motion** [comment]
Hi Thierry, can you elaborate on "it doesn't work"? Do you get an error, or is there something else? Or does nothing happen?

**Comment by dadwarf** [comment]
I'm sorry, it didn't go futher it says that the csv is not valid. The file is a CRLF ANSI encoded one.

**Comment by dadwarf** [comment]
In fact with only this two lines it goes to "Prepare Import" but with this :
![image](https://user-images.githubusercontent.com/43446209/128626101-0c8cd322-cefa-41ee-af63-a006d20c6f1b.png)

**Comment by dadwarf** [comment]
with this tree ones

06/08/2021,"ACHAT CB GVB VOERTUIG B 05.08.21 EUR         12.80 CARTE NO  222  ",-12.80,-83.96
06/08/2021,"ACHAT CB CRV WWW.EPSILO 05.08.21 EUR          1.00 CARTE NO  222  ",-1.00,-6.56
05/08/2021,"PRELEVEMENT DE GAZ ET ELECTRICIT E GRENOBLE REF : EC0208202118697 GEG electricite EC0208202118697",-50.00,-327.98

Error : 
![image](https://user-images.githubusercontent.com/43446209/128626170-e032396f-d7d8-4bac-8b76-103a50d7b195.png)

**Comment by range-of-motion** [comment]
Hey, apologies for the late reply. 

When you see the 3 inputs for "date", "description" and "amount", you need to select which column represents which. In your case I'll give an example.

| Date | Description | Amount |
| ----- | ----------- | -------- |
| 06/08/2021 | "ACHAT CB GVB VOERTUIG..." | -12.80  |

Once you have configured these columns and press "Submit", it should work. If you have any more questions, please let me know, I'd be happy to help 🙂

**Comment by range-of-motion** [comment]
@dadwarf did you ever get this resolved? If I don't hear anything I'm going to assume you did 🙂

**Comment by range-of-motion** [comment]
Closing this as I haven't heard from you, but let me know if it ever happens again.
