### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by zabbidou** [range-of-motion/budget#323]
I don't know much about docker and the things this app is trying to do, but here are some error messages I've received after running `docker-compose up`

```
app_1       | 2021-08-16 11:51:45,368 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140204862773512 for <Subprocess at 140204863168456 with name php-fpm in state STARTING> (stderr)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])

app_1       | Warning: require(/var/www/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/bootstrap/autoload.php on line 17
app_1       |
app_1       | Fatal error: require(): Failed opening required '/var/www/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/bootstrap/autoload.php on line 17

app_1       | 2021-08-16 11:51:45,471 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140204862774304 for <Subprocess at 140204862771352 with name queue-worker in state STARTING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
app_1       | 2021-08-16 11:51:51,733 INFO exited: queue-worker (exit status 255; not expected)
app_1       | 2021-08-16 11:51:52,735 INFO gave up: queue-worker entered FATAL state, too many start retries too quickly
```

To mention, I am using the branch `148-revamp-docker-setup` after having the issue with PHP versions #320 . I am building it on WSL2 with Docker for windows, with the wsl2 integration installed

**Comment by range-of-motion** [comment]
I'm having no issues whatsoever on `148-revamp-docker-setup`. Does the autoloader actually exist? 

I recommend you run the container in the background (`docker-compose up -d`), and then running `docker-compose exec app composer install` to install the dependencies and generate the autoloader.

Hope that helps. If not, let me know and I'll have another look.

**Comment by kazuyoshi-tech** [comment]
Sorry, I didn't notice the reply for a long time.

In my environment (docker for mac version 20.10.7),when I executed `docker-compose up -d` command, composer install could not be done and an error occurred.

if it is no problem, I close the issue and PR.
thank you!!

**Comment by levijackson** [comment]
In case anyone else runs into it, I'm on a mac as well. After running `docker-compose up -d` I had to manually run the steps in the `docker_boot.sh` file.

`docker-compose exec bash` to connect to the docker container
```
composer install
cp .env.docker .env
php artisan key:generate
php artisan storage:link

yarn install
yarn production

php artisan migrate --force
```

**Comment by range-of-motion** [comment]
@levijackson thanks for the tip.

That would indicate the same problem as #369? That it can't find `docker_boot.sh`?

**Comment by levijackson** [comment]
@range-of-motion yeah, that sounds exactly like what I had ran into

**Comment by range-of-motion** [comment]
@levijackson could you check if you still get that problem? And if so, which operating system you're on?

**Comment by range-of-motion** [comment]
As this issue has gotten stale, I assume this is no longer an issue. If I'm wrong, please re-open or create another issue 🙂
