### ISSUE TITLE
Author hosted demo configured incorrectly in nginx

### ISSUE THREAD

**Issue by halfk1ng** [range-of-motion/budget#324]
**Expected behavior**

Redirect to live instance hosted by authors.

**Current behavior**

Redirecting to generic nginx page.

**Steps to reproduce**

1. See https://github.com/range-of-motion/budget/blob/master/README.md
2. Click on hyperlink "using the instance hosted by us." href=https://budgethq.com/
3. See destination output

**Comment by range-of-motion** [comment]
I'm aware of the problem and I'm aiming to bring it back soon. Apologies for the delay.

**Comment by range-of-motion** [comment]
This aged well. Anyway, like I said in the other issue (#393), I have clarified this in the `README.md`. When I can find the time to bring it back up, I will.
