### ISSUE TITLE
Create a docker image on docker hub

### ISSUE THREAD

**Issue by DerKnerd** [range-of-motion/budget#367]
I would love to install the app on my server, but keeping docker images up to date without knowing when a new version is released is hard. Could you maybe create a workflow to create docker images on every tag?

**Comment by pawisoon** [comment]
This would be fantastic to have to bring the project to much more users! Any update on status of this?  @range-of-motion

**Comment by range-of-motion** [comment]
I'm putting this on the roadmap ✌️

**Comment by range-of-motion** [comment]
Currently preparing our Docker setup for this. `v0.15.0` should be the first version that gets published on Docker Hub.

**Comment by range-of-motion** [comment]
[Here you go](https://hub.docker.com/r/rangeofmotion/budget).
