### ISSUE TITLE
Translate Vue-components

### ISSUE THREAD

**Issue by sebastiaanspeck** [range-of-motion/budget#370]
**Expected behavior**

The Vue-components should use the translations from lang-folder.

**Current behavior**

The Vue-components aren't translated.

**Steps to reproduce**

1. Set the language to something else than English.
2. Go to transactions/create.
3. The Vue-components TransactionWizard isn't translated.

<img width="839" alt="image" src="https://user-images.githubusercontent.com/12570668/200338534-fdc746d2-148d-438a-97d0-a78c2170b75b.png">

**Comment by range-of-motion** [comment]
I'll be closing this, as we're heading into a different direction in general (moving from server-sided rendering using Blade to a Vue app).
