### ISSUE TITLE
Bad URL in README

### ISSUE THREAD

**Issue by FireFingers21** [range-of-motion/budget#393]
Line 11 of the README.md file contains a URL (https://budgethq.com) which redirects to a site selling the domain for $2500 USD at (https://www.squadhelp.com/name/BudgetHQ).

**Comment by range-of-motion** [comment]
You're absolutely right. I had planned to fix this earlier, and bring the hosted link back up, however I haven't been able to find the time for this (yet). In the meanwhile, I have clarified this in the `README.md`.
