### ISSUE TITLE
Missing required parameter for [Route: reports.show]

### ISSUE THREAD

**Issue by Boni619** [range-of-motion/budget#400]
![Dashboard-Budget](https://github.com/range-of-motion/budget/assets/28540285/91c8b03b-b3b3-4139-8f72-a403b34d0785)

# When I click on the report I am getting this  error

![Missing-required-parameter-for-Route-reports-show-URI-reports-report-Missing-parameter-report-View-Users-boni-Sites-php-projects-budget-resources-views-reports-index-blade-php-500-Internal-Server-Error- (1)](https://github.com/range-of-motion/budget/assets/28540285/f43fbf1f-3e4f-420b-8039-f341cae5be45)

*I am creating a PR to fix this issue*

**Comment by range-of-motion** [comment]
Done in #427.
