### ISSUE TITLE
Allow recurrings to be an earning

### ISSUE THREAD

**Issue by Pandabehr** [range-of-motion/budget#5]
Since salary is usually a recurring earning, but rent is a recurring spending.

My idea, if the amount is negative put it down as a spending.  
Which makes a positive amount an earning.

Or you could add a type of recurring, so you dont have to fill out negative amounts ever.

**Comment by range-of-motion** [comment]
I like it. Give this man a raise. I'll start working on it.

**Comment by sebastiaanspeck** [comment]
Any update on this? I got some spare time during the weekends to work on this

**Comment by Pandabehr** [comment]
i would love that, this product is UNUSABLE without it.

**Comment by sebastiaanspeck** [comment]
I will look into it tonight. I think I can reuse the transaction.create view to acomplish it

**Comment by sebastiaanspeck** [comment]
Implements #40

**Comment by range-of-motion** [comment]
Done in #122.
