### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by range-of-motion** [range-of-motion/budget#52]
Thinking of starting with versioning soon. It's kinda hard to know for an end-user what features and changes they have access to, and I think it'd be good to for example display the version or tag on the "community edition".

Thoughts?

**Comment by sebastiaanspeck** [comment]
Looks a good idea to me. Let's start using semantic versioning and keep a CHANGELOG.md which can also be published to the "community edition"

**Comment by range-of-motion** [comment]
Time to get on with this.

* Before the first release I'd like to merge migrations. This would massively declutter the files in that folder, and I think we can still get away with it before out first tagged version.. 😂 
* The first version will be v0.1.0, and we will work our way towards v1.0.0.

**Comment by range-of-motion** [comment]
Migrations were merged in #81.

**Comment by range-of-motion** [comment]
v0.1.0 just got tagged, therefor this issue can be closed.
