### ISSUE TITLE
Issue templates and expand CONTRIBUTING.md

### ISSUE THREAD

**Issue by range-of-motion** [range-of-motion/budget#58]
Are issue templates even a thing on GitHub?

**Comment by sebastiaanspeck** [comment]
> Are issue templates even a thing on GitHub?

Well.. it can help users to make more descriptive issues, but it's not a form, so users can also just throw away the predefined text...

**Comment by sebastiaanspeck** [comment]
I have an example [here](https://github.com/sebastiaanspeck/matchy/tree/master/.github/ISSUE_TEMPLATE) for you

**Comment by range-of-motion** [comment]
Done in #65.
