### ISSUE TITLE
No filetype sanitazation in upload form

### ISSUE THREAD

**Issue by CorneJB** [range-of-motion/budget#74]
**Expected behavior**

Only being able to upload data formats that make sense to be uploaded, like csv or other table formats

**Current behavior**

Every single filetype can be uploaded (with constraints on size), this can lead to unexpected behavior and could even be a security risk.

**Steps to reproduce**

1. Go to main page and click imports (https://app.budget.pixely.me/imports)
2. Upload image or other nonsensical data
3. click next and see nonsensical data in tables

**Comment by range-of-motion** [comment]
Thanks for reporting this, I will look into it!

**Comment by range-of-motion** [comment]
@CorneJB I just pushed #78, can you let me know if that fixes your issue?

**Comment by range-of-motion** [comment]
I went ahead and merged it (in #78), assuming this was what fixed your issue.
