### ISSUE TITLE
Improve pages for logging in and registering

### ISSUE THREAD

**Issue by range-of-motion** [range-of-motion/budget#87]
* Automatically focus on e-mail input (upon page load)
* Tweak styling a bit
  * Modify colors
  * Show logo(?)
  * Steal bits and pieces from Tailwind and Bootstrap

**Comment by range-of-motion** [comment]
![Untitled2](https://user-images.githubusercontent.com/9268822/81477268-258b2300-9217-11ea-833e-98c1f387cb49.png)

**Comment by ryangjchandler** [comment]
I think the "Forgot your password?" makes more sense above the "Log in" button...

**Comment by range-of-motion** [comment]
Fair point, updated it 👍

**Comment by range-of-motion** [comment]
Done in #88.
