### ISSUE TITLE
Attach receipt as image or PDF to transaction

### ISSUE THREAD

**Issue by range-of-motion** [range-of-motion/budget#89]
Would this be a useful feature?

**Comment by range-of-motion** [comment]
Removing this from the v0.2 milestone as I have no clear indication of whether or not this is a useful feature.

**Comment by AsteroidSnowsuit** [comment]
This would be so useful. I'm going to start working on it ASAP.

**Comment by AsteroidSnowsuit** [comment]
I will start working on this soon.

**Comment by range-of-motion** [comment]
Make sure to push your code so we can review it along the way, and help if needed.

**Comment by range-of-motion** [comment]
Done in #131.
